# https://taskfile.dev

version: "3"

interval: 500ms

tasks:
  default:
    desc: Lists tasks
    cmd: task -a

  install-dependencies:
    desc: Installs npm dependencies
    cmds:
      - npm install
    sources:
      - package.json
      - package-lock.json

  tailwind:
    desc: Builds tailwind css
    cmds:
      - npx tailwindcss -i ./assets/tailwind.css -o ./assets/dist/tailwind.css
    sources:
      - "**/*.html.templ"
    generates:
      - "assets/dist/tailwind.css"
    deps:
      - install-dependencies

  generate:
    desc: Generates templ Go files
    cmds:
      - go generate ./...
    sources:
      - "**/*.html.templ"
    generates:
      - "**/*.html_templ.go"

  build:
    desc: Builds the to Go binary
    deps:
      - generate
      - tailwind
    cmds:
      - CGO_ENABLED=0 go build -o to{{exeExt}} cmd/server/main.go
    sources:
      - "**/*.go"
      - "assets/dist/tailwind.css"
      - "domains/config/default.yaml"
    generates:
      - "to{{exeExt}}"

  dev:
    desc: Runs the to binary, rebuilding and restarting when sources are updated
    deps:
      - build
    watch: true
    sources:
      - config.yaml
    cmds:
      - "to{{exeExt}}"
