# https://taskfile.dev

version: "3"

interval: 500ms

tasks:
  default:
    deps:
      - build
  deps:
    cmds:
      - npm install
    sources:
      - package.json
      - package-lock.json
  generate:
    cmds:
      - go generate ./...
    sources:
      - "**/*.html.templ"
    generates:
      - "**/*.html_templ.go"
  tailwind:
    cmds:
      - npx tailwindcss -i ./assets/tailwind.css -o ./assets/dist/tailwind.css
    sources:
      - "**/*.html.templ"
    generates:
      - "assets/dist/tailwind.css"
    deps:
      - deps
  build:
    deps:
      - generate
      - tailwind
    cmds:
      - CGO_ENABLED=0 go build -o to cmd/server/main.go
    sources:
      - "**/*.go"
      - "assets/dist/tailwind.css"
  dev:
    deps:
      - build
    watch: true
    cmd: ./to
