name: Tag Releases

on:
  push:
    branches:
      - main

jobs:
  tag-releases:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Install Task
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Install Templ
        run: go install github.com/a-h/templ/cmd/templ@latest

      - name: Build
        run: task build

      - name: Test
        run: task test

      - name: Tag New Release
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          WITH_V: true
